/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.Biblioteca;
import control.MyJFrame;

/**
 *
 * @author dam
 */
public class VntInicio extends MyJFrame {

    Biblioteca miBiblioteca;
    PanelLogin panelLogin;
    PanelUsuario panelUsuario;

    /**
     * Creates new form VntInicio
     */
    public VntInicio() {
        miBiblioteca = new Biblioteca();
        miBiblioteca.createAdmin();
        miBiblioteca.cargarLibros();
        centrar();
        initComponents();
        showLogin();

    }

    public VntInicio(Biblioteca miBiblioteca) {
        this.miBiblioteca = miBiblioteca;
        centrar();
        initComponents();
        showLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestión de alquileres");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cierre();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public void eliminarPanel() {
        try {
            this.remove(panelLogin);
        } catch (Exception ex) {
        }
        try {
            this.remove(panelUsuario);
        } catch (Exception ex) {
        }
    }

    public void showLogin() {
        eliminarPanel();
        panelLogin = new PanelLogin(miBiblioteca, this);
        this.getContentPane().add(panelLogin);
        pack();
    }

    public void showRegister() {
        eliminarPanel();
        panelUsuario = new PanelUsuario(miBiblioteca, this);
        getContentPane().add(panelUsuario);
        pack();
    }

    public void chargeVntControl() {
        new VtnOperaciones(miBiblioteca).setVisible(true);
        this.dispose();
        this.pack();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VntInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VntInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VntInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VntInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VntInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables

}
