/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.Mail;
import control.MyJFrame;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author satan
 */
public class WinControl extends MyJFrame {

    Mail myMail;
    PanelSignUp panelSignUp;
    PanelDemolish panelDemolish;
    PanelConsult panelConsult;
    PanelChangePass panelChangePass;
    User activeUser;

    public WinControl() {
    }

    public WinControl(Mail myMail, User user) {
        initComponents();
        this.myMail = myMail;
        activeUser = user;
        if (user.getPermission() == User.USER) {//Si es un usuario no puede usar estos paneles
            mnuSingUp.setVisible(false);
            mnuDemolish.setVisible(false);
            mnuConsult.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuChangePass = new javax.swing.JMenuItem();
        mnuSingUp = new javax.swing.JMenuItem();
        mnuDemolish = new javax.swing.JMenuItem();
        mnuConsult = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuDisconnect = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Correo");
        setMinimumSize(new java.awt.Dimension(400, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("Opciones");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mnuChangePass.setText("Cambiar contraseña");
        mnuChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChangePassActionPerformed(evt);
            }
        });
        jMenu1.add(mnuChangePass);

        mnuSingUp.setText("Dar de alta");
        mnuSingUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSingUpActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSingUp);

        mnuDemolish.setText("Dar de baja");
        mnuDemolish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDemolishActionPerformed(evt);
            }
        });
        jMenu1.add(mnuDemolish);

        mnuConsult.setText("Condulta usuarios");
        mnuConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsult);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        mnuDisconnect.setText("Desconectar");
        mnuDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDisconnectActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDisconnect);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void mnuDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDisconnectActionPerformed
        new WinLoging(myMail).setVisible(true);
        dispose();
        pack();
    }//GEN-LAST:event_mnuDisconnectActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Cierra el programa con comprobación
        cerrar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuSingUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSingUpActionPerformed
        clean();
        panelSignUp = new PanelSignUp(myMail);
        this.getContentPane().add(panelSignUp);
        pack();
    }//GEN-LAST:event_mnuSingUpActionPerformed

    private void mnuDemolishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDemolishActionPerformed
        clean();
        panelDemolish = new PanelDemolish(myMail, activeUser);
        this.getContentPane().add(panelDemolish);
        pack();
    }//GEN-LAST:event_mnuDemolishActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mnuConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultActionPerformed
        clean();
        panelConsult = new PanelConsult(myMail);
        this.getContentPane().add(panelConsult);
        pack();
    }//GEN-LAST:event_mnuConsultActionPerformed

    private void mnuChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChangePassActionPerformed
        //Comprueba si es un usuario y luego si tiene la contraseña del mismo
        boolean permission = false;
        if (activeUser.getPermission() == User.USER) {
            if (JOptionPane.showInputDialog(this,
                    "Necesaria contraseaña para continuar",
                    "Confirmar identidad", JOptionPane.INFORMATION_MESSAGE)
                    .equals(activeUser.getPass())) {
                permission = true;
            }else{
                JOptionPane.showMessageDialog(this, "Contraseña incorrecta",
                        "Error",JOptionPane.WARNING_MESSAGE);
            }
            
        } else {
            permission = true;
        }

        if (permission) {
            clean();
            panelChangePass=new PanelChangePass(activeUser, myMail);
            this.getContentPane().add(panelChangePass);
            pack();
        }
    }//GEN-LAST:event_mnuChangePassActionPerformed

    private void clean() {
        try {
            this.remove(panelSignUp);
        } catch (Exception ex) {

        }
        try {
            this.remove(panelDemolish);
        } catch (Exception ex) {

        }
        try {
            this.remove(panelConsult);
        } catch (Exception ex) {

        }
        try {
            this.remove(panelChangePass);
        } catch (Exception ex) {

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuChangePass;
    private javax.swing.JMenuItem mnuConsult;
    private javax.swing.JMenuItem mnuDemolish;
    private javax.swing.JMenuItem mnuDisconnect;
    private javax.swing.JMenuItem mnuSingUp;
    // End of variables declaration//GEN-END:variables
}
